service:
  name: uzilog-edge

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

package:
  exclude:
    - node_modules/**

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource: "arn:aws:dynamodb:ap-northeast-2:*:*"

functions:
  myLambdaAtEdge2:
    handler: src/viewer.request;
    events:
      - cloudFront:
          eventType: viewer-request
          origin:
            DomainName: duyf5qolb14b6.cloudfront.net
            OriginPath: /*
          authorizer: aws_iam
